import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F5EFDF',
  },
  safeArea: {
    flex: 1,
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
  },
  header: {
    minHeight: 84,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    minWidth: 42,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pressed: {
    opacity: 0.55,
  },
  brandMark: {
    width: 98,
    height: 72,
    borderWidth: 2,
    borderStyle: 'dotted',
    borderColor: '#171511',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-1deg' }],
  },
  brandText: {
    color: '#11100E',
    textAlign: 'center',
    fontSize: 22,
    lineHeight: 19,
    fontWeight: '900',
    letterSpacing: -1.5,
  },
  searchWrap: {
    height: 48,
    marginHorizontal: 22,
    marginBottom: 12,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#EAE2D0',
  },
  searchIcon: {
    width: 24,
    height: 24,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#1D1A15',
    paddingVertical: 8,
  },
  feed: {
    paddingHorizontal: 18,
    paddingBottom: 14,
    alignItems: 'center',
  },
  postCard: {
    width: '100%',
    marginBottom: 22,
  },
  postAuthor: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    gap: 10,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#60765D',
    backgroundColor: '#D5C8AE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEmoji: {
    fontSize: 23,
  },
  username: {
    color: '#161410',
    fontWeight: '800',
    fontSize: 15,
  },
  moreButton: {
    marginLeft: 'auto',
    fontSize: 27,
    color: '#28241C',
    letterSpacing: 1,
    paddingHorizontal: 5,
  },
  poster: {
    width: '100%',
    aspectRatio: 0.84,
    maxHeight: 520,
    minHeight: 360,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#BBAF94',
    justifyContent: 'center',
    alignItems: 'center',
  },
  posterPager: {
    width: '100%',
    aspectRatio: 0.84,
    maxHeight: 520,
    minHeight: 360,
    overflow: 'hidden',
  },
  posterPagination: {
    height: 29,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  posterDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#B9B5AC',
  },
  posterDotActive: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4C9BD8',
  },
  postDetails: {
    paddingHorizontal: 18,
    paddingVertical: 13,
    justifyContent: 'flex-start',
    backgroundColor: '#F9F4E9',
  },
  postDetailsEyebrow: {
    color: '#857B67',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 2,
  },
  postDetailsTitle: {
    marginTop: 4,
    marginBottom: 7,
    color: '#1D1A15',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  cityMap: {
    height: 144,
    overflow: 'hidden',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D4C9B4',
    backgroundColor: '#E6E8D8',
  },
  cityMapSurface: StyleSheet.absoluteFill,
  cityMapCaption: {
    position: 'absolute',
    top: 9,
    left: 9,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: 'rgba(249, 244, 233, 0.94)',
  },
  cityMapEyebrow: {
    color: '#857B67',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  cityMapName: {
    marginTop: 2,
    color: '#1D1A15',
    fontSize: 13,
    fontWeight: '900',
  },
  cityMapEmpty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  cityMapEmptyTitle: {
    color: '#857B67',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  cityMapEmptyText: {
    marginTop: 4,
    color: '#655D4F',
    fontSize: 11,
    textAlign: 'center',
  },
  cityMapWeb: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  posterMap: {
    height: 100,
  },
  modalMap: {
    height: 260,
  },
  postDetailsSection: {
    marginTop: 9,
    marginBottom: 5,
    color: '#A5422E',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.5,
  },
  postDetailsPlace: {
    minHeight: 25,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: '#D9CFBC',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  postDetailsNumber: {
    width: 34,
    color: '#9B8D74',
    fontSize: 12,
    fontWeight: '800',
  },
  postDetailsPlaceName: {
    flex: 1,
    color: '#25221C',
    fontSize: 13,
    fontWeight: '700',
  },
  postDetailsDescription: {
    marginTop: 9,
    color: '#655D4F',
    fontSize: 12,
    lineHeight: 16,
  },
  posterLeftField: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '24%',
  },
  posterRightField: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '25%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'stretch',
  },
  checkerTile: {
    width: '50%',
    height: '25%',
    backgroundColor: 'rgba(255, 242, 218, 0.2)',
  },
  checkerTileAlternate: {
    backgroundColor: 'rgba(35, 30, 22, 0.12)',
  },
  sideLetters: {
    position: 'absolute',
    zIndex: 3,
    left: '3%',
    top: '20%',
    gap: 5,
  },
  letterToken: {
    width: 38,
    height: 38,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#C8BFA9',
    backgroundColor: '#F8F2E4',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#201A11',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  letterTokenText: {
    color: '#171511',
    fontSize: 20,
    fontWeight: '900',
  },
  collagePhotoTop: {
    position: 'absolute',
    left: '7%',
    top: '7%',
    width: 84,
    height: 106,
    borderColor: '#FFF9EB',
    borderWidth: 4,
    backgroundColor: '#E6CBA1',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-7deg' }],
    zIndex: 1,
  },
  collagePhotoBottom: {
    position: 'absolute',
    left: '6%',
    bottom: '5%',
    width: 98,
    height: 84,
    borderColor: '#FFF9EB',
    borderWidth: 4,
    backgroundColor: '#E7D6B8',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '8deg' }],
    zIndex: 1,
  },
  collagePhotoEmoji: {
    fontSize: 49,
  },
  posterDecorationTop: {
    position: 'absolute',
    top: '5%',
    left: '31%',
    right: '27%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1,
  },
  decorEmoji: {
    fontSize: 34,
  },
  decorSparkle: {
    color: '#F7ECD5',
    fontSize: 40,
  },
  paper: {
    zIndex: 2,
    width: '70%',
    minHeight: '64%',
    paddingHorizontal: 12,
    paddingVertical: 14,
    alignItems: 'stretch',
    justifyContent: 'center',
    backgroundColor: '#F9F4E9',
    borderColor: '#D6CBB8',
    borderWidth: 1,
    shadowColor: '#261F16',
    shadowOffset: { width: 2, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  posterTitle: {
    textAlign: 'center',
    fontWeight: '900',
    fontSize: 21,
    lineHeight: 23,
    letterSpacing: 0.7,
    marginBottom: 7,
  },
  paperDivider: {
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#8C8578',
    marginBottom: 5,
  },
  placeLine: {
    color: '#25221C',
    fontSize: 13,
    lineHeight: 22,
    fontFamily: Platform.select({ ios: 'Courier', android: 'monospace', default: 'monospace' }),
    fontWeight: '700',
  },
  placeNumber: {
    fontWeight: '900',
  },
  stamp: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 96,
    marginTop: 10,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: '#E23D25',
    transform: [{ rotate: '-2deg' }],
  },
  stampText: {
    color: '#FFF7E9',
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  barcode: {
    width: 48,
    height: 9,
    marginTop: 2,
    backgroundColor: '#171511',
  },
  postageSticker: {
    position: 'absolute',
    zIndex: 3,
    bottom: '8%',
    right: '5%',
    width: 66,
    height: 76,
    backgroundColor: '#F6F0E0',
    borderWidth: 3,
    borderColor: '#FFF9EE',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '11deg' }],
  },
  postageEmoji: {
    fontSize: 31,
  },
  postageCaption: {
    fontSize: 10,
    fontWeight: '900',
    color: '#242019',
  },
  tape: {
    position: 'absolute',
    width: 90,
    height: 26,
    bottom: '5%',
    left: '6%',
    opacity: 0.85,
    transform: [{ rotate: '-8deg' }],
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    height: 29,
  },
  dot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#B9B5AC',
  },
  dotActive: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4C9BD8',
  },
  postActions: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  actionGroup: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionIcon: {
    color: '#11100E',
    fontSize: 31,
    lineHeight: 36,
  },
  likedIcon: {
    color: '#D3412B',
  },
  actionCount: {
    color: '#181611',
    fontSize: 17,
    fontWeight: '700',
  },
  actionSpacer: {
    flex: 1,
  },
  description: {
    marginTop: 2,
    color: '#2B281F',
    fontSize: 13,
    lineHeight: 19,
  },
  moreText: {
    color: '#766F61',
  },
  postDate: {
    marginTop: 3,
    fontSize: 11,
    color: '#81796C',
  },
  bottomBar: {
    minHeight: 62,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F5EFDF',
    borderTopColor: '#E6DDCA',
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  bottomAvatar: {
    width: 39,
    height: 39,
  },
  emptyState: {
    minHeight: 300,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 35,
  },
  emptyStamp: {
    color: '#D14A30',
    fontSize: 47,
  },
  emptyTitle: {
    marginTop: 10,
    color: '#1B1812',
    fontSize: 21,
    fontWeight: '900',
  },
  emptyBody: {
    marginTop: 8,
    color: '#756D60',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 21,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(21, 18, 13, 0.38)',
  },
  backdropDismiss: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: '#F7F1E4',
    paddingTop: 10,
    paddingHorizontal: 22,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '82%',
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#CCC2B0',
    alignSelf: 'center',
    marginBottom: 16,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  sheetTitle: {
    flex: 1,
    color: '#1A1712',
    fontSize: 21,
    fontWeight: '900',
  },
  closeButton: {
    fontSize: 30,
    lineHeight: 31,
    color: '#28241D',
    paddingLeft: 14,
  },
  form: {
    gap: 10,
  },
  fieldLabel: {
    marginTop: 6,
    color: '#6E6659',
    fontSize: 10,
    letterSpacing: 1.1,
    fontWeight: '800',
  },
  formInput: {
    minHeight: 48,
    paddingHorizontal: 13,
    color: '#201C16',
    backgroundColor: '#EEE6D7',
    borderRadius: 10,
    fontSize: 15,
  },
  placesInput: {
    minHeight: 86,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  primaryButton: {
    minHeight: 50,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D7472D',
    borderRadius: 11,
  },
  disabledButton: {
    opacity: 0.55,
  },
  primaryButtonText: {
    color: '#FFF7E9',
    fontSize: 16,
    fontWeight: '900',
  },
  modalContent: {
    paddingBottom: 12,
  },
  commentCount: {
    color: '#71695D',
    marginBottom: 14,
    fontSize: 13,
  },
  commentCard: {
    flexDirection: 'row',
    gap: 10,
    padding: 13,
    backgroundColor: '#EEE6D7',
    borderRadius: 12,
  },
  commentAvatar: {
    fontSize: 23,
  },
  commentText: {
    flex: 1,
    color: '#28241C',
    fontSize: 14,
    lineHeight: 21,
  },
  commentInput: {
    minHeight: 46,
    marginTop: 14,
    paddingHorizontal: 13,
    borderRadius: 10,
    backgroundColor: '#EEE6D7',
    color: '#211E18',
  },
  modalFootnote: {
    marginTop: 12,
    color: '#6F685C',
    fontSize: 13,
  },
  profileContent: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  profileAvatar: {
    width: 76,
    height: 76,
    borderRadius: 40,
  },
  profileName: {
    marginTop: 12,
    color: '#1C1913',
    fontSize: 18,
    fontWeight: '900',
  },
  profileNote: {
    maxWidth: 270,
    marginTop: 7,
    color: '#71695D',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  profileStats: {
    marginTop: 18,
    color: '#D0472D',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
});
